services:
  backend:
    container_name: wiki-backend
    build:
      context: ./backend
      dockerfile: ../Dockerfile-backend
    ports:
      - "9000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    container_name: wiki-frontend
    build:
      context: ./frontend
      dockerfile: ../Dockerfile-frontend
    ports:
      - "9500:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - backend

  nginx:
    container_name: wiki-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
